#!/usr/bin/env python3
"""Write the WiX fragment that puts Lang/ into the MSI.

There are ninety-odd language files and each one needs its own component, so
the fragment is generated from whatever is in the staged Lang directory
rather than kept by hand and left to drift.

    python3 .github/scripts/gen_lang_wxs.py <staged Lang dir> <output .wxs>

The main wxs declares <Directory Id="LangFolder" Name="Lang" /> under
INSTALLFOLDER and references the group as <ComponentGroupRef Id="CG_Lang" />.
"""
import os
import re
import sys

GROUP = "CG_Lang"
DIRECTORY = "LangFolder"

HEAD = """<?xml version="1.0" encoding="utf-8"?>

<!-- Generated by .github/scripts/gen_lang_wxs.py - do not edit. -->

<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Fragment>
    <ComponentGroup Id="%s" Directory="%s">
""" % (GROUP, DIRECTORY)

TAIL = """    </ComponentGroup>
  </Fragment>
</Wix>
"""


def identifier(name):
    """A WiX Id: letters, digits and underscore, not starting with a digit."""
    ident = re.sub(r"[^0-9A-Za-z_]", "_", name)
    if not ident or not (ident[0].isalpha() or ident[0] == "_"):
        ident = "_" + ident
    return ident


def main(argv):
    if len(argv) != 2:
        sys.stderr.write(__doc__)
        return 2
    lang_dir, out_path = argv

    names = sorted(n for n in os.listdir(lang_dir)
                   if os.path.isfile(os.path.join(lang_dir, n)))
    if not names:
        sys.stderr.write("error: %s holds no file\n" % lang_dir)
        return 2

    seen = {}
    parts = [HEAD]
    for name in names:
        ident = identifier(name)
        if ident in seen:
            sys.stderr.write("error: %s and %s both give the id %s\n"
                             % (seen[ident], name, ident))
            return 2
        seen[ident] = name
        parts.append(
            '      <Component Id="C_Lang_%s" Guid="*" Win64="yes">\n'
            '        <File Id="F_Lang_%s" Source="$(var.BinDir)\\Lang\\%s" KeyPath="yes" />\n'
            '      </Component>\n' % (ident, ident, name))
    parts.append(TAIL)

    with open(out_path, "w", encoding="utf-8", newline="\r\n") as fh:
        fh.write("".join(parts))
    print("%s: %d language files" % (out_path, len(names)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
