[workspace]
resolver = "3"
members = ["crates/*"]
default-members = ["crates/archive-cli"]

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.97.1"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
